name: Release

on:
  schedule:
    #schedule build every night
    # - cron: "0/10 * * * *"
    # - cron: "0 1 * * *"
  push:
    branches: [ master ]

#on:
#  push:
#    branches: [ master ]

jobs:
  update:
    name: Update build status
    runs-on: ubuntu-20.04
    steps:
      - name: sync github release
        id: create_release
        uses: h-twinkle/sync-action@master
        with:
          debug: false
          gitee_owner: Htwinkle
          gitee_repo: sync-repo
          gitee_token: ${{ secrets.gitee_token }}
          github_owner: rustdesk
          github_repo: rustdesk
          gitee_upload_retry_times: 3
