name: Release

on:
  schedule:
    #schedule build every night
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update build status
    runs-on: ubuntu-20.04
    steps:
      - name: sync github release
        id: create_release
        uses: h-twinkle/sync-action@master
        with:
          gitee_owner: Htwinkle
          gitee_repo: sync-repo
          gitee_token: ${{ secrets.gitee_token }}
          github_owner: movsb
          github_repo: http2tcp
          gitee_upload_retry_times: 3
